spring:
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html

  datasource:
    url: jdbc:h2:tcp://localhost/~/jpashop
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create # 애플리케이션 실행시점에 일단 내가가진 엔티티를 다 지우고, 다시 생성하는 auto 기능 (만약 none으로 두면 데이터 새로고침 안함!)
    properties:
      hibernate:
#        show_sql: true # 이건 sout에 출력하는 것 (상용환경에서는 쓰면 안됨)
        format_sql: true
        default_batch_fetch_size: 100 # where in 쿼리를 최대 몇개까지 날리게 허용할 것인가에 대한 옵션!
        # 가령 2로 설정했는데 최대가 4인게 있다면 2씩 두번 쿼리 날리게 됨 (걍 엥간하면 100 ~ 1000으로 둬라!: db 성능에 따라 잘 설정)
        # 단, 이건 글로벌 적용이고 디테일하게 적용할하려면 엔티티마다 필요에 맞게 @BatchSize 라는 애노테이션으로 size 설정해주면 됨 (근데 글로벌 써 그냥 ㅋㅋ)
#    open-in-view: false

editor:
  soft:
    wrap:
      force:
        limit=100000:

logging:
  level:
    org.hibernate.SQL: debug # 이건 logger로 출력하는 것 (상용환경에서 써도 되는 것)
#    org.hibernate.type: trace